pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKERHUB_REPO = 'ibirikambiri/messaging-app'
        APP_DIR = 'messaging_app'
    }

    stages {
        stage('Install dependencies & Test') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        python -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                        pytest --junitxml=pytest-report.xml
                    '''
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir("${APP_DIR}") {
                    sh "docker build -t $DOCKERHUB_REPO:latest ."
                }
            }
        }

        stage('Push Docker image') {
            steps {
                withDockerRegistry([credentialsId: "${DOCKERHUB_CREDENTIALS}", url: ""]) {
                    sh "docker push $DOCKERHUB_REPO:latest"
                }
            }
        }
    }
}
